#! /bin/bash
sudo yum update -y 
sudo yum install httpd -y httpd
sudo systemctl restart httpd
sudo systemctl enable httpd
sudo echo "Hello from Web Instance" > /var/www/html/index.html
sudo chown -R apache:apache/var/www/html
